import {test} from 'node:test';import assert from 'node:assert/strict';import worker,{validSignal,digest,equal,randomKey} from '../src/worker.mjs';
test('signal envelope excludes file bodies and malformed session IDs',()=>{const m={type:'offer',session:'a'.repeat(32),sdp:'v=0',mac:'b'.repeat(64)};assert(validSignal(m));assert(!validSignal({...m,type:'file'}));assert(!validSignal({...m,sdp:'x'.repeat(50001)}));assert(!validSignal({...m,session:'../other'}));});
test('registration is disabled by default and requires operator key',async()=>{for(const env of [{},{REGISTRATION_ENABLED:'true',ENROLLMENT_KEY:'secret'}]){const r=await worker.fetch(new Request('https://example.org/rooms',{method:'POST'}),env);assert.equal(r.status,403);}});
test('untrusted origins rejected before room access',async()=>{const r=await worker.fetch(new Request('https://example.org/health',{headers:{Origin:'https://evil.org'}}),{});assert.equal(r.status,403);});
test('health permits bundled phone origin and does not expose keys',async()=>{const r=await worker.fetch(new Request('https://example.org/health',{headers:{Origin:'https://appassets.androidplatform.net'}}),{TURN_API_TOKEN:'secret'});assert.equal(r.status,200);assert(!(await r.text()).includes('secret'));assert.equal(r.headers.get('Cache-Control'),'no-store');});
test('credentials are random capabilities stored as hashes',async()=>{assert.notEqual(randomKey(),randomKey());assert.equal(randomKey().length,43);assert.equal((await digest('x')).length,64);assert(equal('abc','abc'));assert(!equal('abc','abd'));});

test('automatic enrollment fails closed without admission limits',async()=>{const r=await worker.fetch(new Request('https://example.org/enroll',{method:'POST',body:'{}'}),{AUTO_ENROLLMENT_ENABLED:'true'});assert.equal(r.status,503)});
test('automatic enrollment has a separate operator kill switch',async()=>{const r=await worker.fetch(new Request('https://example.org/enroll',{method:'POST',body:'{}'}),{AUTO_ENROLLMENT_ENABLED:'false'});assert.equal(r.status,403)});
