using System.Diagnostics;
using Microsoft.Win32;
using ActionBridge.Core;

namespace ActionBridge.Windows;

public sealed partial class BridgeForm {
    static readonly Color Accent=Color.FromArgb(18,126,118),Ink=Color.FromArgb(29,43,57),Muted=Color.FromArgb(91,105,115);
    readonly Label sendHeading=new(){AutoSize=true,Font=new("Segoe UI",21,FontStyle.Bold)};
    readonly Label sendHint=new(){AutoSize=true,MaximumSize=new(540,0),ForeColor=Muted};
    readonly Label recent=new(){AutoSize=true,MaximumSize=new(540,0),ForeColor=Muted};
    Button fileButton=null!,textButton=null!,clipboardButton=null!;
    string? selectedDevice;bool refreshingDevices,stagingFiles;
    public BridgeForm(){
        Text="ActionBridge";Size=new(1120,780);MinimumSize=new(850,620);Font=new("Segoe UI",10);AutoScaleMode=AutoScaleMode.Dpi;
        BackColor=Color.FromArgb(244,247,250);ForeColor=Ink;Icon=Icon.ExtractAssociatedIcon(Environment.ProcessPath!)??SystemIcons.Application;tray.Icon=Icon;
        try{selectedDevice=File.ReadAllText(Path.Combine(root,"selected-device.txt"));}catch{}
        var shell=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=1,RowCount=2,Padding=new(22)};
        shell.RowStyles.Add(new(SizeType.Absolute,95));shell.RowStyles.Add(new(SizeType.Percent,100));Controls.Add(shell);
        var header=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=2};header.ColumnStyles.Add(new(SizeType.Percent,100));header.ColumnStyles.Add(new(SizeType.Absolute,150));
        var brand=Column();brand.Controls.Add(Title("ActionBridge",24));status.ForeColor=Muted;brand.Controls.Add(status);header.Controls.Add(brand);
        header.Controls.Add(ActionButton("Add device",AddDevice,true),1,0);shell.Controls.Add(header,0,0);
        var tabs=new TabControl{Dock=DockStyle.Fill,Padding=new(24,12)};shell.Controls.Add(tabs,0,1);
        var home=new TabPage("Home"){BackColor=BackColor,Padding=new(16)};var activity=new TabPage("Activity"){BackColor=Color.White,Padding=new(16)};var settings=new TabPage("Settings"){BackColor=Color.White,Padding=new(16)};
        tabs.TabPages.AddRange([home,activity,settings]);
        var layout=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=2,RowCount=1};layout.ColumnStyles.Add(new(SizeType.Percent,34));layout.ColumnStyles.Add(new(SizeType.Percent,66));home.Controls.Add(layout);
        var devicePanel=new TableLayoutPanel{Dock=DockStyle.Fill,RowCount=4,ColumnCount=1,Padding=new(16),BackColor=Color.White,Margin=new(0,0,16,0)};
        devicePanel.RowStyles.Add(new(SizeType.Absolute,44));devicePanel.RowStyles.Add(new(SizeType.Absolute,45));devicePanel.RowStyles.Add(new(SizeType.Percent,100));devicePanel.RowStyles.Add(new(SizeType.Absolute,44));
        devicePanel.Controls.Add(Title("Your devices",15),0,0);devicePanel.Controls.Add(Description("Select where you want to send."),0,1);devicePanel.Controls.Add(sendTarget,0,2);
        devicePanel.Controls.Add(ActionButton("Manage selected device",ManageSelectedDevice),0,3);layout.Controls.Add(devicePanel,0,0);
        sendTarget.DrawItem+=(_,e)=>{if(e.Index<0)return;var p=(SendPhone)sendTarget.Items[e.Index];bool selected=(e.State&DrawItemState.Selected)!=0;using var brush=new SolidBrush(selected?Color.FromArgb(228,244,241):Color.White);e.Graphics.FillRectangle(brush,e.Bounds);var split=p.Label.LastIndexOf(" · ");var name=split<0?p.Label:p.Label[..split];var route=split<0?"Saved device":p.Label[(split+3)..];using var nameFont=new Font(Font,FontStyle.Bold);TextRenderer.DrawText(e.Graphics,name,nameFont,new Rectangle(e.Bounds.X+Px(12),e.Bounds.Y+Px(10),e.Bounds.Width-Px(24),Px(24)),Ink,TextFormatFlags.EndEllipsis);TextRenderer.DrawText(e.Graphics,route,Font,new Rectangle(e.Bounds.X+Px(12),e.Bounds.Y+Px(35),e.Bounds.Width-Px(24),Px(22)),Muted,TextFormatFlags.EndEllipsis);e.DrawFocusRectangle();};
        sendTarget.SelectedIndexChanged+=(_,_)=>{if(!refreshingDevices){selectedDevice=(sendTarget.SelectedItem as SendPhone)?.Id;try{Directory.CreateDirectory(root);File.WriteAllText(Path.Combine(root,"selected-device.txt"),selectedDevice??"");}catch{}UpdateSendControls();}};
        var workspace=Column();workspace.Dock=DockStyle.Fill;workspace.AutoScroll=true;workspace.Padding=new(16);workspace.BackColor=Color.White;layout.Controls.Add(workspace,1,0);
        workspace.Controls.Add(sendHeading);workspace.Controls.Add(sendHint);workspace.Controls.Add(Description("FILES",true));
        var drop=Description("Drop files here, or choose them below.\nThe receiver gets a saved copy.");drop.Padding=new(18);drop.BackColor=Color.FromArgb(244,247,250);drop.MinimumSize=new(400,100);workspace.Controls.Add(drop);
        fileButton=ActionButton("Send files…",async()=>{using var picker=new OpenFileDialog{Multiselect=true,Title="Choose files to send"};if(picker.ShowDialog(this)==DialogResult.OK)await QueueFiles(picker.FileNames,fileButton);},true);fileButton.Width=220;workspace.Controls.Add(fileButton);
        workspace.Controls.Add(Description("TEXT & LINKS",true));var textRow=new FlowLayoutPanel{AutoSize=true,WrapContents=true};textButton=ActionButton("Write text or link",SendText);clipboardButton=ActionButton("Send clipboard",SendClipboard);textRow.Controls.AddRange([textButton,clipboardButton]);workspace.Controls.Add(textRow);
        workspace.Controls.Add(Description("For a phone, keep ActionBridge open and select this computer.\nFor another computer, leave its receiver running."));workspace.Controls.Add(Description("LATEST SENT ITEM",true));workspace.Controls.Add(recent);
        workspace.Controls.Add(ActionButton("View all activity",()=>tabs.SelectedTab=activity));
        workspace.SizeChanged+=(_,_)=>{var width=Math.Max(200,workspace.ClientSize.Width-workspace.Padding.Horizontal-24);foreach(Control child in workspace.Controls)if(child is Label label)label.MaximumSize=new(width,0);drop.MinimumSize=new(Math.Min(400,width),100);};
        DpiChanged+=(_,_)=>sendTarget.ItemHeight=Px(66);
        foreach(Control target in new Control[]{home,workspace,drop}){target.AllowDrop=true;target.DragEnter+=(_,e)=>{if(!stagingFiles&&sendTarget.SelectedItem!=null&&e.Data?.GetDataPresent(DataFormats.FileDrop)==true)e.Effect=DragDropEffects.Copy;};target.DragDrop+=async(_,e)=>{if(e.Data?.GetData(DataFormats.FileDrop) is string[] paths)await QueueFiles(paths,fileButton);};}
        var records=new TabControl{Dock=DockStyle.Fill};activity.Controls.Add(records);var receivedPage=new TabPage("Received");var sentPage=new TabPage("Sent");records.TabPages.AddRange([receivedPage,sentPage]);
        history.BorderStyle=BorderStyle.None;history.FullRowSelect=true;history.HideSelection=false;history.Columns.Add("When",145);history.Columns.Add("Item / action",260);history.Columns.Add("Route",90);history.Columns.Add("Status",145);history.Columns.Add("Details",300);history.SizeChanged+=(_,_)=>history.Columns[4].Width=Math.Max(160,history.ClientSize.Width-650);
        history.DoubleClick+=(_,_)=>OpenSelectedReceived();receivedPage.Controls.Add(history);emptyActivity.Text="Nothing received yet.\nAdd a device to start sharing with this computer.";receivedPage.Controls.Add(emptyActivity);
        var receiveTools=new FlowLayoutPanel{Dock=DockStyle.Bottom,Height=58};receiveTools.Controls.Add(ActionButton("Open selected file",OpenSelectedReceived));receiveTools.Controls.Add(ActionButton("Received folder",OpenFolder));var cancel=ActionButton("Cancel transfer",async()=>{if(history.SelectedItems.Count>0&&history.SelectedItems[0].Tag is Job j){await transfers!.Cancel(j.Request.Id,j.ClientId);RefreshHistory();}});cancel.Enabled=false;receiveTools.Controls.Add(cancel);history.SelectedIndexChanged+=(_,_)=>cancel.Enabled=history.SelectedItems.Count>0&&history.SelectedItems[0].Tag is Job j&&j.State is "uploading" or "queued";receivedPage.Controls.Add(receiveTools);
        sent.HorizontalScrollbar=true;sent.BorderStyle=BorderStyle.None;sent.ItemHeight=34;sentPage.Controls.Add(sent);var sendTools=new FlowLayoutPanel{Dock=DockStyle.Bottom,Height=58};var cancelSent=ActionButton("Cancel selected item",()=>{if(sent.SelectedItem is SentItem item){outbox?.Cancel(item.Item.Id);RefreshSent();}});cancelSent.Enabled=false;sent.SelectedIndexChanged+=(_,_)=>cancelSent.Enabled=sent.SelectedItem is SentItem item&&item.Item.State is "queued" or "sending" or "retrying";sendTools.Controls.Add(cancelSent);sentPage.Controls.Add(sendTools);
        var prefs=Column();prefs.Dock=DockStyle.Fill;prefs.AutoScroll=true;prefs.Padding=new(16);settings.Controls.Add(prefs);prefs.Controls.Add(Title("Receiving & startup",17));
        var startup=new CheckBox{Text="Start receiving when I sign in",AutoSize=true,Margin=new(0,12,0,12)};using(var key=Registry.CurrentUser.OpenSubKey(@"Software\Microsoft\Windows\CurrentVersion\Run"))startup.Checked=key?.GetValue("ActionBridge")!=null;startup.CheckedChanged+=(_,_)=>{using var key=Registry.CurrentUser.CreateSubKey(@"Software\Microsoft\Windows\CurrentVersion\Run");if(startup.Checked)key.SetValue("ActionBridge","\""+Environment.ProcessPath+"\" --tray");else key.DeleteValue("ActionBridge",false);};prefs.Controls.Add(startup);
        prefs.Controls.Add(Description("Closing this window keeps receiving in the system tray.\nChoose Quit from the tray menu to stop."));prefs.Controls.Add(ActionButton("Open received folder",OpenFolder));prefs.Controls.Add(Title("Printing",17));prefs.Controls.Add(Description("Add printers in Windows Settings. On your phone, choose Print to select\npaper, copies and other options. A submitted job is not a physical print confirmation."));prefs.Controls.Add(ActionButton("Windows printer settings",()=>Process.Start(new ProcessStartInfo("ms-settings:printers"){UseShellExecute=true})));
        prefs.Controls.Add(Title("Connection help",17));prefs.Controls.Add(Description("Nearby: use the same Wi-Fi or Ethernet and approve the connection.\nInternet: add a device using this computer’s private code. Keep both devices awake.\nAn unavailable device stays saved. Internet connections depend on both networks."));prefs.Controls.Add(ActionButton("Show this computer’s QR code",ShowCode));prefs.Controls.Add(ActionButton("Remove internet access",async()=>{if(remote==null||MessageBox.Show(this,"Revoke this computer’s QR code and remove internet access?","Remove internet access",MessageBoxButtons.YesNo)!=DialogResult.Yes)return;try{await remote.Disconnect();RefreshSendTargets();}catch(Exception e){MessageBox.Show(this,e.Message);}}));
        prefs.Controls.Add(Title("Connection details",17));remoteStatus.AutoSize=true;prefs.Controls.Add(remoteStatus);prefs.Controls.Add(Description("ActionBridge 0.7.0 · No advertising or analytics.\nPairing codes grant access to this computer. Share them only with devices you trust."));
        remoteRetry.Tick+=async(_,_)=>{if(remote?.Enabled==true){if(remote.Config!=null)remote.Start();else await EnsureRemote();}};remoteRetry.Start();activityTimer.Tick+=(_,_)=>{if(historyDirty){historyDirty=false;RefreshHistory();RefreshSent();}};activityTimer.Start();
        var menu=new ContextMenuStrip();menu.Items.Add("Open ActionBridge",null,(_,_)=>ShowWindow());menu.Items.Add("Received files",null,(_,_)=>OpenFolder());menu.Items.Add("Quit",null,async(_,_)=>{exiting=true;computers?.Dispose();remote?.Stop();if(server!=null)await server.DisposeAsync();tray.Visible=false;Close();});tray.ContextMenuStrip=menu;tray.DoubleClick+=(_,_)=>ShowWindow();FormClosing+=(_,e)=>{if(!exiting){e.Cancel=true;Hide();}};Shown+=async(_,_)=>{sendTarget.ItemHeight=Px(66);await Start();};UpdateSendControls();
    }
    static FlowLayoutPanel Column()=>new(){FlowDirection=FlowDirection.TopDown,WrapContents=false,AutoSize=false,Dock=DockStyle.Fill};
    static Label Title(string value,int size)=>new(){Text=value,Font=new("Segoe UI",size,FontStyle.Bold),AutoSize=true,Margin=new(0,8,0,12)};
    static Label Description(string value,bool heading=false)=>new(){Text=value,AutoSize=true,MaximumSize=new(620,0),ForeColor=heading?Accent:Muted,Font=new("Segoe UI",heading?9:10,heading?FontStyle.Bold:FontStyle.Regular),Margin=new(0,heading?24:8,0,12)};
    static Button ActionButton(string value,Action action,bool primary=false){var b=new Button{Text=value,AutoSize=true,MinimumSize=new(140,44),Height=44,Padding=new(12,4,12,4),FlatStyle=FlatStyle.Flat,BackColor=primary?Accent:Color.FromArgb(228,244,241),ForeColor=primary?Color.White:Accent,Cursor=Cursors.Hand,Margin=new(0,6,10,10)};b.FlatAppearance.BorderSize=0;b.Click+=(_,_)=>action();return b;}
    void UpdateSendControls(){var device=sendTarget.SelectedItem as SendPhone;sendHeading.Text=device==null?"Ready to share":("Send to "+device.Label.Split(" · ")[0]);sendHeading.MaximumSize=new(Math.Max(200,(sendHeading.Parent?.ClientSize.Width??500)-56),0);sendHint.Text=device==null?"Add a device, then select it on the left.":"Files, text and links go to the selected device.";if(fileButton!=null){fileButton.Enabled=device!=null&&outbox!=null&&!stagingFiles;textButton.Enabled=clipboardButton.Enabled=fileButton.Enabled;}recent.Text=outbox?.History().FirstOrDefault() is {} item?item.Name+" · "+FriendlyState(item.State):"No transfers yet. Your history appears in Activity.";}
    void OpenFolder(){Directory.CreateDirectory(received);Process.Start(new ProcessStartInfo(received){UseShellExecute=true});}
    void OpenSelectedReceived(){if(history.SelectedItems.Count>0&&history.SelectedItems[0].Tag is Job j&&transfers!=null&&File.Exists(transfers.Destination(j)))Process.Start(new ProcessStartInfo(transfers.Destination(j)){UseShellExecute=true});}
    async void ShowCode(){if(remote==null)return;try{await EnsureRemote(true);if(remote.Config!=null)remote.ShowPairing(this);}catch(Exception e){MessageBox.Show(this,e.Message,"Could not show pairing code");}}
    void AddDevice(){using var d=new Form{Text="Add a device",Size=new(490,390),StartPosition=FormStartPosition.CenterParent,FormBorderStyle=FormBorderStyle.FixedDialog,MaximizeBox=false,MinimizeBox=false};var p=Column();p.Padding=new(24);d.Controls.Add(p);p.Controls.Add(Title("What are you connecting?",18));p.Controls.Add(Description("Install ActionBridge on the other device first."));p.Controls.Add(ActionButton("A phone · show QR code",()=>{d.Close();ShowCode();},true));p.Controls.Add(ActionButton("A computer · find nearby",async()=>{d.Close();await DiscoverComputers();}));p.Controls.Add(ActionButton("A computer · enter address or code",async()=>{d.Close();await AddComputer();}));p.Controls.Add(Description("To receive from another computer, show your QR code\nand copy it into Add device on that computer."));d.ShowDialog(this);}
    void ManageSelectedDevice(){if(sendTarget.SelectedItem is not SendPhone target){MessageBox.Show(this,"Select a device on Home first.");return;}if(target.Id.StartsWith("remote:")){ShowCode();return;}if(MessageBox.Show(this,"Remove "+target.Label.Split(" · ")[0]+"? You can add it again later.","Remove device",MessageBoxButtons.YesNo)!=DialogResult.Yes)return;if(computers?.Contains(target.Id)==true)computers.Remove(target.Id);else trust?.Revoke(target.Id);selectedDevice=null;RefreshSendTargets();}
    async void SendText(){if(outbox==null||sendTarget.SelectedItem is not SendPhone target)return;using var d=new Form{Text="Send to "+target.Label.Split(" · ")[0],Size=new(540,350),StartPosition=FormStartPosition.CenterParent};var entry=new TextBox{Multiline=true,Dock=DockStyle.Fill,MaxLength=8192,Margin=new(16)};var hint=new Label{Text="Text is copied on a computer. Web links can be opened on the receiver.",Dock=DockStyle.Top,Height=55,Padding=new(12)};var go=new Button{Text="Send text or link",Dock=DockStyle.Bottom,Height=48,DialogResult=DialogResult.OK};d.Controls.Add(entry);d.Controls.Add(hint);d.Controls.Add(go);if(d.ShowDialog(this)!=DialogResult.OK)return;await StageText(target.Id,entry.Text);}
    async void SendClipboard(){if(sendTarget.SelectedItem is SendPhone target)await StageText(target.Id,Clipboard.ContainsText()?Clipboard.GetText():"");}
    async Task StageText(string recipient,string value){try{value=value.Trim();if(string.IsNullOrEmpty(value))throw new ArgumentException("Enter or copy some text first.");var kind=Uri.TryCreate(value,UriKind.Absolute,out var u)&&u.Scheme is "http" or "https"?"link":"text";await outbox!.Stage(recipient,null,value,kind);RefreshSent();}catch(Exception e){MessageBox.Show(this,e.Message,"Could not send");}}
    static string FriendlyState(string value)=>value switch{"queued"=>"Waiting to send","uploading" or "sending"=>"Transferring","retrying"=>"Waiting for device","completed"=>"Completed","saved"=>"Saved","submitted"=>"Sent to printer","delivered"=>"Delivered","running"=>"Performing action","uncertain"=>"Check receiver / printer","cancelled" or "canceled"=>"Canceled","failed"=>"Needs attention",_=>System.Globalization.CultureInfo.CurrentCulture.TextInfo.ToTitleCase(value)};
    int Px(int value)=>(int)Math.Round(value*DeviceDpi/96d);
    static string Bytes(long size)=>size>=1048576?$"{size/1048576d:0.#} MB":size>=1024?$"{size/1024d:0.#} KB":$"{size} B";
}
