using ActionBridge.Core;
using ActionBridge.Ubuntu;
using System.Security.Cryptography;
using System.Text.Json;
using System.Runtime.Versioning;
[assembly: SupportedOSPlatform("linux")]
var passes=0;void Check(bool value,string name){if(!value)throw new Exception(name);passes++;Console.WriteLine("PASS: "+name);}
async Task Reject(Func<Task> run,string name){try{await run();throw new Exception("Expected rejection: "+name);}catch(InvalidOperationException){Check(true,name);}catch(ArgumentException){Check(true,name);}}
var runner=new FixtureCommands();var desktopCalls=new List<string>();var actions=new LinuxActions(runner,(method,value)=>{desktopCalls.Add(method);return Task.FromResult(JsonSerializer.SerializeToElement(method=="clipboard"?new{copied=true}:(object)new{opened=true}));});
var printers=await actions.ListPrinters();Check(printers.Count==1&&printers[0].IsDefault,"CUPS default printer discovered");Check(printers[0].Papers.SequenceEqual(new[]{"A4","Letter"}),"CUPS default paper marker removed");Check(printers[0].SupportsColor&&printers[0].SupportsDuplex,"CUPS color and duplex capabilities exposed");
var id=Guid.NewGuid().ToString();var r=new JobRequest(id,"invoice.pdf",123,new string('a',64),"print",Printer:"Office",Copies:3,Landscape:true,Paper:"A4",Color:true,Fit:"fill",Duplex:"long",PageFrom:2,PageTo:4,Collate:false);
var arguments=LinuxActions.PrintArguments(r,"/tmp/folder with spaces/$(touch nope).pdf");Check(arguments[^2]=="--"&&arguments[^1].Contains("$(touch"),"file path remains one literal argument after option terminator");Check(arguments.Contains("sides=two-sided-long-edge"),"duplex maps to CUPS long edge");Check(arguments.Contains("orientation-requested=4")&&arguments.Contains("Collate=False"),"orientation and collation preserved");Check(arguments.Contains("print-scaling=fill")&&arguments.Contains("media=A4"),"scaling and paper preserved");Check(arguments.Contains("2-4")&&arguments[1]=="3","page range and copies preserved");
await actions.ExecuteAsync(r,"/tmp/invoice.pdf");Check(runner.Submissions==1,"validated print submits once");await Reject(()=>actions.ExecuteAsync(r with{PageTo=8},"/tmp/invoice.pdf"),"PDF range beyond document rejected before submission");Check(runner.Submissions==1,"invalid range does not submit");await Reject(()=>actions.ExecuteAsync(r with{Paper="Unavailable"},"/tmp/invoice.pdf"),"unknown paper rejected");await Reject(()=>actions.ExecuteAsync(r with{Printer="Unknown"},"/tmp/invoice.pdf"),"unknown printer rejected");
await actions.ExecuteAsync(new(id,"Text",0,"","copy",Text:"क clipboard"),null);Check(desktopCalls.Contains("clipboard"),"clipboard delivered through desktop pipe");await actions.ExecuteAsync(new(id,"Link",0,"","url",Text:"https://example.com"),null);Check(desktopCalls.Contains("open"),"link uses desktop association without shell execution");await Reject(()=>actions.ExecuteAsync(new(id,"Link",0,"","url",Text:"javascript:alert(1)"),null),"script URL blocked");await Reject(()=>actions.ExecuteAsync(r with{Action="open"},"/tmp/script.desktop"),"downloaded executable desktop entry never auto-opens");Check(LinuxActions.AllowedOpen("/tmp/report.PDF")&&!LinuxActions.AllowedOpen("/tmp/file.sh"),"file-opening whitelist is case-insensitive and excludes scripts");
runner.PrintFail=true;await Reject(()=>actions.ExecuteAsync(r,"/tmp/invoice.pdf"),"ambiguous CUPS failure is surfaced rather than claimed successful");runner.PrintFail=false;
var root=Path.Combine(Path.GetTempPath(),"actionbridge-linux-test-"+Guid.NewGuid());Directory.CreateDirectory(root);var sink=new CountingSink();var transfers=new Transfers(Path.Combine(root,"jobs"),Path.Combine(root,"files"),sink,"Submitted to CUPS; physical printing is not confirmed.");var bytes=new byte[]{1,2,3};var job=r with{Id=Guid.NewGuid().ToString(),Size=3,Sha256=Convert.ToHexString(SHA256.HashData(bytes)).ToLowerInvariant()};await transfers.Create(job,"phone");await transfers.Append(job.Id,"phone",0,new MemoryStream(bytes),3,CancellationToken.None);await Task.WhenAll(Enumerable.Range(0,10).Select(_=>transfers.Finish(job.Id,"phone")));for(int i=0;i<200&&transfers.Get(job.Id,"phone").State is "queued" or "running";i++)await Task.Delay(10);Check(sink.Count==1,"concurrent finish retries cannot duplicate Linux printing");Check(transfers.Get(job.Id,"phone").Message!.Contains("CUPS"),"Ubuntu print activity names the correct queue");
var outbox=new Outbox(Path.Combine(root,"outbox"));outbox.Changed+=()=>throw new Exception("UI unavailable");var file=Path.Combine(root,"test.txt");await File.WriteAllTextAsync(file,"hello");var outgoing=await outbox.Stage("phone",file);outbox.Acknowledge(outgoing.Id,"phone");Check(outbox.History().Single().State=="delivered"&&!File.Exists(Path.Combine(root,"outbox",outgoing.Id+".payload")),"UI observer failure cannot interrupt durable acknowledgement or payload cleanup");var orphan=Guid.NewGuid()+".payload";await File.WriteAllTextAsync(Path.Combine(root,"outbox",orphan),"partial");_ = new Outbox(Path.Combine(root,"outbox"));Check(!File.Exists(Path.Combine(root,"outbox",orphan)),"abandoned staging body cleaned on restart");
Directory.Delete(root,true);Console.WriteLine($"\n{passes} Ubuntu checks passed.");
sealed class CountingSink:IActionSink{public int Count;public Task ExecuteAsync(JobRequest r,string? f){Interlocked.Increment(ref Count);return Task.CompletedTask;}public IReadOnlyList<PrintChoice> Printers()=>[];}
sealed class FixtureCommands:ICommands{public int Submissions;public bool PrintFail;public Task<CommandResult> Run(string executable,IEnumerable<string> arguments,int timeoutSeconds=20){var args=arguments.ToArray();var result=executable switch{"/usr/bin/lpstat" when args[0]=="-p"=>new(0,"printer Office is idle. enabled\n",""),"/usr/bin/lpstat"=>new(0,"system default destination: Office\n",""),"/usr/bin/lpoptions"=>new(0,"PageSize/Page Size: *A4 Letter\nColorModel/Color: Gray *RGB\nDuplex/Two-sided: *None DuplexNoTumble DuplexTumble\n",""),"/usr/bin/pdfinfo"=>new(0,"Pages:          5\n",""),"/usr/bin/lp"=>new(PrintFail?1:0,"request id is Office-1\n",PrintFail?"printer unavailable":""),_=>new CommandResult(0,"","")};if(executable=="/usr/bin/lp")Submissions++;return Task.FromResult(result);}}
