using ActionBridge.Core;
using System.Security.Cryptography;
using System.Text.Json;
using System.Net;
using System.Net.Sockets;
var passed=0;var failed=0;
void Check(bool condition,string message){if(!condition)throw new Exception(message);passed++;Console.WriteLine("PASS: "+message);}
var root=Path.Combine(Path.GetTempPath(),"ab-computer-"+Guid.NewGuid());Directory.CreateDirectory(root);
try {
 var aRoot=Path.Combine(root,"a");var bRoot=Path.Combine(root,"b");Directory.CreateDirectory(aRoot);Directory.CreateDirectory(bRoot);var aId=Guid.NewGuid().ToString();var bId=Guid.NewGuid().ToString();var sinkA=new Sink();var sinkB=new Sink();var aJobs=new Transfers(Path.Combine(aRoot,"jobs"),Path.Combine(aRoot,"received"),sinkA);var bJobs=new Transfers(Path.Combine(bRoot,"jobs"),Path.Combine(bRoot,"received"),sinkB);var aBox=new Outbox(Path.Combine(aRoot,"outbox"));var bBox=new Outbox(Path.Combine(bRoot,"outbox"));using var cert=ServerIdentity.Load(ServerIdentity.CreatePfx());var trust=new TrustStore(bRoot);var allow=true;using var sock=new TcpListener(IPAddress.Loopback,0);sock.Start();var port=((IPEndPoint)sock.LocalEndpoint).Port;sock.Stop();await using var server=new BridgeServer(bId,"Ubuntu receiver",cert,trust,bJobs,sinkB,(_,_)=>Task.FromResult(allow),outbox:bBox);await server.StartAsync(port,false);
 var computers=new Computers(aRoot,aId,"Windows sender",aBox,aJobs);await computers.AddLocal("127.0.0.1",port);var peer=computers.List().Single();Check(trust.Authenticate(peer.Token)==aId,"receiving computer explicitly approves sender identity");
 var source=Path.Combine(root,"कंप्यूटर.txt");var bytes=RandomNumberGenerator.GetBytes(800000);await File.WriteAllBytesAsync(source,bytes);var item=await aBox.Stage(peer.Recipient,source);await File.WriteAllTextAsync(source,"original changed");await computers.Pump(peer);var saved=bJobs.Get(item.Id,aId);Check(saved.State=="completed"&&File.ReadAllBytes(bJobs.Destination(saved)).SequenceEqual(bytes),"Computer-to-computer TLS transfer saves immutable snapshot with verified bytes");Check(aBox.History().Single().State=="delivered"&&!File.Exists(Path.Combine(aRoot,"outbox",item.Id+".payload")),"destination confirmation commits delivery and deletes sender body");await computers.Pump(peer);Check(bJobs.History().Length==1&&sinkB.Count==1,"repeat pump does not duplicate a saved file or action");
 await File.WriteAllBytesAsync(source,bytes);var reverse=await bBox.Stage(aId,source);await computers.Pump(peer);var incoming=aJobs.Get(reverse.Id,peer.Recipient);Check(incoming.State=="completed"&&File.ReadAllBytes(aJobs.Destination(incoming)).SequenceEqual(bytes),"Reverse computer delivery uses the same approved connection");Check(bBox.History().Single().State=="delivered","reverse source releases its queue after local durable save");
 Check(!JsonSerializer.Serialize(computers.Snapshot()).Contains(peer.Token),"public desktop snapshot excludes authentication token");computers.Dispose();computers=new Computers(aRoot,aId,"Windows sender",aBox,aJobs);Check(computers.List().Single().Token==peer.Token,"destination and credentials persist across restart");
 var wrong=peer with{Fingerprint=new string('0',64)};using(var bad=new LanComputerTransport(wrong)){Check(await Fails(()=>bad.Call("hello")),"saved certificate mismatch is rejected");}using(var bad=new LanComputerTransport(peer with{Token=new string('b',64)})){Check(await Fails(()=>bad.Call("outbox")),"unapproved credential cannot read receiver outbox");}
 var faulted=false;computers.Dispose();computers=new Computers(aRoot,aId,"Windows sender",aBox,aJobs,factory:p=>new Fault(new LanComputerTransport(p),async(method,result)=>{if(method=="append"&&!faulted){faulted=true;throw new IOException("lost chunk acknowledgement");}await Task.CompletedTask;}));var resumed=await aBox.Stage(peer.Recipient,source);await computers.Pump(peer);Check(bJobs.Get(resumed.Id,aId).Offset==262144&&aBox.List(peer.Recipient).Single().Id==resumed.Id,"lost upload acknowledgement preserves committed offset and queued source");await computers.Pump(peer);Check(bJobs.Get(resumed.Id,aId).State=="completed"&&aBox.History().Single(x=>x.Id==resumed.Id).State=="delivered","retry resumes same job identity after lost acknowledgement");
 computers.Dispose();var lostFinish=false;computers=new Computers(aRoot,aId,"Windows sender",aBox,aJobs,factory:p=>new Fault(new LanComputerTransport(p),async(method,result)=>{if(method=="finish"&&!lostFinish){lostFinish=true;throw new IOException("lost finish acknowledgement");}await Task.CompletedTask;}));var finish=await aBox.Stage(peer.Recipient,source);await computers.Pump(peer);var before=sinkB.Count;await computers.Pump(peer);Check(sinkB.Count==before&&aBox.History().Single(x=>x.Id==finish.Id).State=="delivered","lost final reply does not repeat destination action on retry");
 computers.Dispose();Outgoing? cancelled=null;computers=new Computers(aRoot,aId,"Windows sender",aBox,aJobs,factory:p=>new Fault(new LanComputerTransport(p),async(method,result)=>{if(method=="append"&&cancelled!=null)aBox.Cancel(cancelled.Id);await Task.CompletedTask;}));cancelled=await aBox.Stage(peer.Recipient,source);await computers.Pump(peer);Check(bJobs.Get(cancelled.Id,aId).State=="cancelled"&&aBox.History().Single(x=>x.Id==cancelled.Id).State=="cancelled","cancellation between chunks stops destination job and does not resurrect queue");
 var zero=Path.Combine(root,"empty.txt");File.WriteAllBytes(zero,[]);var empty=await aBox.Stage(peer.Recipient,zero);await computers.Pump(peer);Check(bJobs.Get(empty.Id,aId).State=="completed"&&new FileInfo(bJobs.Destination(bJobs.Get(empty.Id,aId))).Length==0,"empty computer file is saved and acknowledged");
 var waiting=await aBox.Stage(peer.Recipient,source);computers.Remove(peer.Recipient);Check(computers.List().Length==0&&aBox.History().Single(x=>x.Id==waiting.Id).State=="cancelled","removing saved computer cancels waiting transfers");computers.Dispose();
 Check(Reject(()=>ComputerRules.Local("8.8.8.8",45833))&&Reject(()=>ComputerRules.Local("example.com",45833)),"nearby setup rejects public and DNS endpoints");Check(Reject(()=>ComputerRules.Pairing("abremote:bad")),"malformed internet pairing rejected before transport start");
 var code="abremote:"+Convert.ToBase64String(JsonSerializer.SerializeToUtf8Bytes(new{id=bId,name="Ubuntu",service="https://example.com",room=new string('a',32),key=new string('b',43),secret=new string('c',43)})).TrimEnd('=').Replace('+','-').Replace('/','_');using var remoteSaved=new Computers(aRoot,aId,"Sender",aBox,aJobs);remoteSaved.AddRemote(code);Check(remoteSaved.List().Single().Internet&&!JsonSerializer.Serialize(remoteSaved.Snapshot()).Contains(code),"internet destination persists while pairing code stays out of snapshots");
 // A declined request must not leave a saved destination.
 var deniedRoot=Path.Combine(root,"denied");Directory.CreateDirectory(deniedRoot);allow=false;using var denied=new Computers(deniedRoot,Guid.NewGuid().ToString(),"Denied",aBox,aJobs);Check(await Fails(()=>denied.AddLocal("127.0.0.1",port))&&denied.List().Length==0,"declined approval does not persist a destination");
} catch(Exception e){failed++;Console.WriteLine("FAIL: "+e);}finally{Directory.Delete(root,true);}
Console.WriteLine($"{passed} computer checks passed; {failed} failed.");return failed==0?0:1;
static async Task<bool> Fails(Func<Task> task){try{await task();return false;}catch{return true;}}
static bool Reject(Action action){try{action();return false;}catch(ArgumentException){return true;}}
sealed class Sink:IActionSink{public int Count;public Task ExecuteAsync(JobRequest r,string? file){Interlocked.Increment(ref Count);return Task.CompletedTask;}public IReadOnlyList<PrintChoice> Printers()=>[];}
sealed class Fault(IComputerTransport inner,Func<string,JsonElement,Task> after):IComputerTransport{public int DownloadSize=>inner.DownloadSize;public async Task<JsonElement> Call(string method,object? values=null,CancellationToken ct=default){var result=await inner.Call(method,values,ct);await after(method,result);return result;}public void Dispose()=>inner.Dispose();}
