using ActionBridge.Core;
using System.Text.Json;
using System.Security.Cryptography;
var passed=0;var failed=0;
async Task Test(string name,Func<string,Task> test){var root=Path.Combine(Path.GetTempPath(),"ab-audit-"+Guid.NewGuid());Directory.CreateDirectory(root);try{await test(root);passed++;Console.WriteLine("PASS: "+name);}catch(Exception ex){failed++;Console.WriteLine("FAIL: "+name+": "+ex.Message);}finally{Directory.Delete(root,true);}}
void Check(bool condition,string message){if(!condition)throw new Exception(message);}
async Task FailedWrite(Func<Task> run){try{await run();throw new Exception("Expected journal write failure.");}catch(IOException){}catch(UnauthorizedAccessException){}}
var bytes=new byte[]{1,2,3};JobRequest Request()=>new(Guid.NewGuid().ToString(),"file.txt",3,Convert.ToHexString(SHA256.HashData(bytes)).ToLowerInvariant(),"save");
await Test("outgoing UI failure cannot prevent acknowledgement or body cleanup",async root=>{var outbox=new Outbox(root);var file=Path.Combine(root,"source");await File.WriteAllBytesAsync(file,bytes);var item=await outbox.Stage("phone",file);outbox.Changed+=()=>throw new Exception("UI gone");outbox.Acknowledge(item.Id,"phone");Check(!File.Exists(Path.Combine(root,item.Id+".payload")),"body retained");});
await Test("failed outgoing journal commit remains queued and retries durably",async root=>{var outbox=new Outbox(root);var file=Path.Combine(root,"source");await File.WriteAllBytesAsync(file,bytes);var item=await outbox.Stage("phone",file);var blocker=Path.Combine(root,item.Id+".json.new");Directory.CreateDirectory(blocker);await FailedWrite(()=>Task.Run(()=>outbox.Acknowledge(item.Id,"phone")));Check(outbox.History().Single().State=="queued","memory says delivered while journal says queued");Directory.Delete(blocker);outbox.Acknowledge(item.Id,"phone");Check(new Outbox(root).History().Single().State=="delivered"&&!File.Exists(Path.Combine(root,item.Id+".payload")),"retry did not persist/remove body");});
await Test("abandoned outgoing staging cleaned without deleting corrupt-journal payload",async root=>{var orphan=Guid.NewGuid().ToString();var damaged=Guid.NewGuid().ToString();await File.WriteAllBytesAsync(Path.Combine(root,orphan+".payload"),bytes);await File.WriteAllBytesAsync(Path.Combine(root,damaged+".payload"),bytes);await File.WriteAllTextAsync(Path.Combine(root,damaged+".json"),"bad journal");_ =new Outbox(root);Check(!File.Exists(Path.Combine(root,orphan+".payload"))&&File.Exists(Path.Combine(root,damaged+".payload")),"orphan policy incorrect");});
await Test("failed upload checkpoint reports only committed offset",async root=>{var t=new Transfers(root,Path.Combine(root,"files"),new Sink());var r=Request();await t.Create(r,"phone");Directory.CreateDirectory(Path.Combine(root,r.Id+".json.new"));await FailedWrite(()=>t.Append(r.Id,"phone",0,new MemoryStream(bytes),3,CancellationToken.None));Check(t.Get(r.Id,"phone").Offset==0&&new FileInfo(Path.Combine(root,r.Id+".part")).Length==0,"uncommitted offset exposed");});
await Test("failed cancellation commit preserves upload state",async root=>{var t=new Transfers(root,Path.Combine(root,"files"),new Sink());var r=Request();await t.Create(r,"phone");Directory.CreateDirectory(Path.Combine(root,r.Id+".json.new"));await FailedWrite(()=>t.Cancel(r.Id,"phone"));Check(t.Get(r.Id,"phone").State=="uploading","uncommitted cancellation exposed");});
await Test("failed finish commit remains safely retryable",async root=>{var t=new Transfers(root,Path.Combine(root,"files"),new Sink());var r=Request();await t.Create(r,"phone");await t.Append(r.Id,"phone",0,new MemoryStream(bytes),3,CancellationToken.None);Directory.CreateDirectory(Path.Combine(root,r.Id+".json.new"));await FailedWrite(()=>t.Finish(r.Id,"phone"));Check(t.Get(r.Id,"phone").State=="uploading","uncommitted queued state exposed");});
await Test("failed approval persistence cannot grant temporary access",async root=>{var trust=new TrustStore(root);var p=new PairRequest(Guid.NewGuid().ToString(),"Phone",new string('a',64));Directory.CreateDirectory(Path.Combine(root,"phones.json.new"));await FailedWrite(()=>Task.Run(()=>trust.Approve(p)));Check(trust.Authenticate(p.Token)==null,"phone granted access despite failed approval save");});
await Test("failed revocation persistence cannot hide still-saved approval",async root=>{var trust=new TrustStore(root);var p=new PairRequest(Guid.NewGuid().ToString(),"Phone",new string('b',64));trust.Approve(p);Directory.CreateDirectory(Path.Combine(root,"phones.json.new"));await FailedWrite(()=>Task.Run(()=>trust.Revoke(p.ClientId)));Check(trust.Authenticate(p.Token)==p.ClientId,"memory and disk trust disagree");});
await Test("large remote clipboard acknowledgement fits one control message",async root=>{var t=new Transfers(root,Path.Combine(root,"files"),new Sink());var remote=new RemoteJobs(t,new Sink(),"room");var r=new JobRequest(Guid.NewGuid().ToString(),"Text",0,"","copy",Text:new string('क',65536));var response=await remote.Dispatch(JsonSerializer.SerializeToElement(new{method="create",job=r},Wire.Json));var encoded=JsonSerializer.SerializeToUtf8Bytes(response,Wire.JsonCompact);Check(encoded.Length<32000,"response is "+encoded.Length+" bytes");});
await Test("failed destination rename releases temporary copy and retains resumable upload",async root=>{var t=new Transfers(root,Path.Combine(root,"files"),new Sink());var r=Request();var j=await t.Create(r,"phone");await t.Append(r.Id,"phone",0,new MemoryStream(bytes),3,CancellationToken.None);var dest=t.Destination(j);Directory.CreateDirectory(dest);await FailedWrite(()=>t.Finish(r.Id,"phone"));Check(!File.Exists(dest+".incoming"),"unsuccessful copy retained in Downloads");Check(t.Get(r.Id,"phone").State=="uploading"&&File.Exists(Path.Combine(root,r.Id+".part")),"source no longer resumable");});
Console.WriteLine($"{passed} audit checks passed; {failed} failed.");return failed==0?0:1;
sealed class Sink:IActionSink{public Task ExecuteAsync(JobRequest r,string? file)=>Task.CompletedTask;public IReadOnlyList<PrintChoice> Printers()=>[];}
