using System.Net;
using System.Net.Sockets;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
namespace ActionBridge.Core;
/** Saved destinations and a durable sender. Desktop files always use Save, never execute. */
public sealed class Computers:IDisposable {
 readonly string path,self,name;readonly Outbox outbox;readonly Transfers inbox;readonly object gate=new();readonly Dictionary<string,ComputerPeer> peers=new();readonly Dictionary<string,string> status=new();readonly Dictionary<string,IComputerTransport> transports=new();readonly Func<byte[],byte[]> protect,unprotect;readonly CancellationTokenSource stop=new();readonly Func<ComputerPeer,IComputerTransport> factory;Task? worker;
 public event Action? Changed;
 public Computers(string root,string self,string name,Outbox outbox,Transfers inbox,Func<byte[],byte[]>? protect=null,Func<byte[],byte[]>? unprotect=null,Func<ComputerPeer,IComputerTransport>? factory=null){this.self=self;this.name=name;this.outbox=outbox;this.inbox=inbox;this.protect=protect??(b=>b);this.unprotect=unprotect??(b=>b);this.factory=factory??(p=>p.Internet?new RemoteComputerTransport(p):new LanComputerTransport(p));path=Path.Combine(root,"computers.dat");if(File.Exists(path)){foreach(var p in JsonSerializer.Deserialize<ComputerPeer[]>(this.unprotect(File.ReadAllBytes(path)),Wire.Json)??[]){Validate(p);peers[p.Recipient]=p;}}}
 static void Validate(ComputerPeer p){if(!Guid.TryParseExact(p.Id,"D",out _)||string.IsNullOrWhiteSpace(p.Name)||p.Name.Length>80)throw new ArgumentException("Invalid computer identity.");if(p.Internet){var j=ComputerRules.Pairing(p.Code!);if(j.GetProperty("id").GetString()!=p.Id)throw new ArgumentException("Computer pairing identity changed.");}else{ComputerRules.Local(p.Host,p.Port);if(p.Fingerprint.Length!=64||!p.Fingerprint.All(Uri.IsHexDigit)||p.Token.Length!=64||!p.Token.All(Uri.IsHexDigit))throw new ArgumentException("Invalid saved computer credentials.");}}
 void Notify(){try{Changed?.Invoke();}catch{}}
 void Save(ComputerPeer p){Validate(p);if(p.Id==self)throw new ArgumentException("Choose a different computer.");lock(gate){if(!peers.ContainsKey(p.Recipient)&&peers.Count>=16)throw new InvalidOperationException("Remove a saved computer before adding another.");var next=new Dictionary<string,ComputerPeer>(peers){[p.Recipient]=p};Store(next.Values.ToArray());peers[p.Recipient]=p;if(transports.Remove(p.Recipient,out var old))old.Dispose();status[p.Recipient]="Waiting for connection";}Notify();}
 void Store(ComputerPeer[] next){var bytes=protect(JsonSerializer.SerializeToUtf8Bytes(next,Wire.Json));using(var file=new FileStream(path+".new",FileMode.Create,FileAccess.Write,FileShare.None)){file.Write(bytes);file.Flush(true);}File.Move(path+".new",path,true);}
 public object[] Snapshot(){lock(gate)return peers.Values.Select(p=>(object)new{id=p.Recipient,name=p.Name,connection=p.Internet?"Internet":"Nearby",status=status.GetValueOrDefault(p.Recipient,"Waiting for connection")}).ToArray();}
 public ComputerPeer[] List(){lock(gate)return peers.Values.ToArray();}
 public bool Contains(string recipient){lock(gate)return peers.ContainsKey(recipient);}
 public void Remove(string recipient){lock(gate){Store(peers.Values.Where(p=>p.Recipient!=recipient).ToArray());peers.Remove(recipient);status.Remove(recipient);if(transports.Remove(recipient,out var t))t.Dispose();}foreach(var item in outbox.ListAll(recipient))outbox.Cancel(item.Id);Notify();}
 public void AddRemote(string code){var j=ComputerRules.Pairing(code.Trim());Save(new(j.GetProperty("id").GetString()!,Wire.SafeName(j.GetProperty("name").GetString()??"Computer")[..Math.Min(80,Wire.SafeName(j.GetProperty("name").GetString()??"Computer").Length)],"",0,"","",code.Trim()));}
 public async Task<ComputerEndpoint> Probe(string host,int port=Wire.ApiPort,CancellationToken ct=default){ComputerRules.Local(host,port);string? pin=null;using var handler=new HttpClientHandler{AllowAutoRedirect=false,ServerCertificateCustomValidationCallback=(_,c,_,_)=>{if(c==null||DateTime.UtcNow<c.NotBefore.ToUniversalTime()||DateTime.UtcNow>c.NotAfter.ToUniversalTime())return false;pin=Convert.ToHexString(SHA256.HashData(c.RawData)).ToLowerInvariant();return true;}};using var client=new HttpClient(handler){Timeout=TimeSpan.FromSeconds(6)};var address=host.Contains(':')?"["+host+"]":host;using var response=await client.GetAsync($"https://{address}:{port}/v1/hello",ct);response.EnsureSuccessStatusCode();var raw=await response.Content.ReadAsStringAsync(ct);if(raw.Length>8192)throw new IOException("Invalid computer response.");var j=JsonSerializer.Deserialize<JsonElement>(raw);var id=j.GetProperty("id").GetString()!;if(!Guid.TryParseExact(id,"D",out _)||id==self||pin!=j.GetProperty("fingerprint").GetString())throw new IOException("Computer identity did not match.");return new(id,(j.GetProperty("name").GetString()??"Computer")[..Math.Min(80,(j.GetProperty("name").GetString()??"Computer").Length)],host,port,pin!);}
 public async Task AddLocal(string host,int port=Wire.ApiPort,CancellationToken ct=default){var endpoint=await Probe(host,port,ct);ComputerPeer? prior;lock(gate)prior=peers.GetValueOrDefault("computer:"+endpoint.Id);if(prior is {Internet:false}&&prior.Fingerprint!=endpoint.Fingerprint)throw new IOException("Computer identity changed. Remove the saved destination before approving it again.");var token=prior is {Internet:false}?prior.Token:Convert.ToHexString(RandomNumberGenerator.GetBytes(32)).ToLowerInvariant();var peer=new ComputerPeer(endpoint.Id,endpoint.Name,host,port,endpoint.Fingerprint,token);using var api=new LanComputerTransport(peer);await api.Call("pair",new PairRequest(self,name,token),ct);Save(peer);}
 public async Task<ComputerEndpoint[]> Discover(CancellationToken ct=default){using var udp=new UdpClient(AddressFamily.InterNetwork);udp.EnableBroadcast=true;udp.Client.Bind(new IPEndPoint(IPAddress.Any,0));var bytes=Encoding.UTF8.GetBytes(Wire.DiscoveryMagic);foreach(var address in new[]{Wire.Group,"255.255.255.255"})await udp.SendAsync(bytes,new IPEndPoint(IPAddress.Parse(address),Wire.DiscoveryPort),ct);var found=new Dictionary<string,ComputerEndpoint>();using var timeout=CancellationTokenSource.CreateLinkedTokenSource(ct);timeout.CancelAfter(TimeSpan.FromSeconds(3));while(!timeout.IsCancellationRequested)try{var packet=await udp.ReceiveAsync(timeout.Token);if(packet.Buffer.Length>8192||!BridgeServer.Local(packet.RemoteEndPoint.Address))continue;var j=JsonSerializer.Deserialize<JsonElement>(packet.Buffer);var e=new ComputerEndpoint(j.GetProperty("id").GetString()!,j.GetProperty("name").GetString()!,packet.RemoteEndPoint.Address.ToString(),j.GetProperty("port").GetInt32(),j.GetProperty("fingerprint").GetString()!);if(e.Id!=self&&Guid.TryParseExact(e.Id,"D",out _))found[e.Id]=e;}catch(OperationCanceledException){break;}catch(JsonException){}catch(KeyNotFoundException){}return found.Values.ToArray();}
 public void Start(){worker??=Task.Run(async()=>{while(!stop.IsCancellationRequested){await Task.WhenAll(List().Select(p=>Pump(p,stop.Token)));try{await Task.Delay(5000,stop.Token);}catch(OperationCanceledException){}}});}
 public async Task Pump(ComputerPeer peer,CancellationToken ct=default){IComputerTransport api;try{lock(gate){if(!peers.ContainsKey(peer.Recipient))return;if(!transports.TryGetValue(peer.Recipient,out api!)){api=factory(peer);transports[peer.Recipient]=api;}}foreach(var item in outbox.List(peer.Recipient))await Push(api,item,ct);await Pull(api,peer,ct);SetStatus(peer,"Connected");}catch(Exception e){if(ct.IsCancellationRequested)return;lock(gate){if(transports.Remove(peer.Recipient,out var broken))broken.Dispose();}SetStatus(peer,e.Message.Length>180?e.Message[..180]:e.Message);}}
 void SetStatus(ComputerPeer p,string value){lock(gate){if(!peers.ContainsKey(p.Recipient)||status.GetValueOrDefault(p.Recipient)==value)return;status[p.Recipient]=value;}Notify();}
 async Task Push(IComputerTransport api,Outgoing item,CancellationToken ct){if(!outbox.ListAll(item.Recipient).Any(x=>x.Id==item.Id&&x.State=="queued"))return;var request=new JobRequest(item.Id,item.Name,item.Size,item.Sha256,item.Kind=="file"?"save":"copy",Text:item.Text);var j=await api.Call("create",new{job=request},ct);try{while(j.GetProperty("state").GetString()=="uploading"&&item.Kind=="file"&&j.GetProperty("offset").GetInt64()<item.Size){if(!outbox.ListAll(item.Recipient).Any(x=>x.Id==item.Id&&x.State=="queued"))throw new OperationCanceledException("Transfer cancelled. A file already saved on the other computer cannot be retracted.");var offset=j.GetProperty("offset").GetInt64();var chunk=JsonSerializer.SerializeToElement(outbox.Read(item.Id,item.Recipient,offset,262144),Wire.JsonCompact);j=await api.Call("append",new{jobId=item.Id,offset,data=chunk.GetProperty("data").GetString()},ct);}if(item.Kind=="file"&&!outbox.ListAll(item.Recipient).Any(x=>x.Id==item.Id&&x.State=="queued"))throw new OperationCanceledException("Transfer cancelled.");if(j.GetProperty("state").GetString() is "uploading" or "queued")j=await api.Call("finish",new{jobId=item.Id},ct);while(j.GetProperty("state").GetString() is "queued" or "running"){await Task.Delay(300,ct);j=await api.Call("status",new{jobId=item.Id},ct);}if(j.GetProperty("state").GetString() is not ("completed" or "submitted"))throw new IOException(j.TryGetProperty("message",out var message)?message.GetString():"Destination did not confirm saving.");outbox.Acknowledge(item.Id,item.Recipient);}catch(OperationCanceledException){try{await api.Call("cancel",new{jobId=item.Id},CancellationToken.None);}catch{}throw;}}
 async Task Pull(IComputerTransport api,ComputerPeer peer,CancellationToken ct){var items=await api.Call("outbox",ct:ct);foreach(var raw in items.EnumerateArray().Take(1)){var item=raw.Deserialize<Outgoing>(Wire.Json)??throw new IOException("Invalid outgoing item.");var request=new JobRequest(item.Id,item.Name,item.Size,item.Sha256,item.Kind=="file"?"save":"copy",Text:item.Text);var job=await inbox.Create(request,peer.Recipient);while(job.State=="uploading"&&item.Kind=="file"&&job.Offset<item.Size){var position=job.Offset;var count=(int)Math.Min(262144,item.Size-position);var calls=new List<Task<JsonElement>>();for(int n=0;n<count;n+=api.DownloadSize)calls.Add(api.Call("download",new{itemId=item.Id,offset=position+n,count=Math.Min(api.DownloadSize,count-n)},ct));var chunks=await Task.WhenAll(calls);using var body=new MemoryStream();foreach(var chunk in chunks){if(chunk.GetProperty("offset").GetInt64()!=position+body.Length)throw new IOException("Download offset changed.");var data=Convert.FromBase64String(chunk.GetProperty("data").GetString()!);if(data.Length!=Math.Min(api.DownloadSize,count-body.Length))throw new IOException("Download length changed.");body.Write(data);}body.Position=0;job=await inbox.Append(item.Id,peer.Recipient,position,body,count,ct);}if(job.State is "uploading" or "queued")job=await inbox.Finish(item.Id,peer.Recipient);while(job.State is "queued" or "running"){await Task.Delay(100,ct);job=inbox.Get(item.Id,peer.Recipient);}if(job.State!="completed")throw new IOException("Received file was not saved. Check activity.");await api.Call("received",new{itemId=item.Id},ct);}}
 public void Dispose(){stop.Cancel();lock(gate){foreach(var t in transports.Values)t.Dispose();transports.Clear();}}
}
