import {test} from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFile} from 'node:fs/promises';import {webcrypto,createHmac} from 'node:crypto';
const source=await readFile(process.env.AUDIT_JS_SOURCE || new URL('app.js',import.meta.url),'utf8');
const until=async fn=>{for(let i=0;i<100;i++){if(fn())return;await new Promise(r=>setTimeout(r,5))}throw Error('fixture timed out')};
function fixture({delayIce=false,stalled=false}={}){
 const config={id:'a',service:'https://a.example',room:'a'.repeat(32),key:'k'.repeat(43),secret:'s'.repeat(43)},next={...config,id:'b',service:'https://b.example',room:'b'.repeat(32),secret:'t'.repeat(43)};
 const elements=Object.fromEntries(['send','status','name'].map(id=>[id,{disabled:false,textContent:''}]));let now=1000,ready=false,retry,resolveIce;const sockets=[],peers=[];class Clock extends Date{static now(){return now}}
 class Channel{constructor(){this.readyState='connecting'}send(){} }
 class Peer{constructor(options){this.origin=options.iceServers[0].urls;this.connectionState='connecting';this.channel=new Channel();peers.push(this)}createDataChannel(){return this.channel}async createOffer(){return{type:'offer',sdp:'offer'}}async setLocalDescription(){}async setRemoteDescription(){this.connectionState='connected';this.channel.readyState='open';this.channel.onopen()}async getStats(){return new Map()}close(){this.channel.readyState='closed';this.channel.onclose?.()}}
 class Socket{constructor(url){this.url=url;this.readyState=stalled?0:1;sockets.push(this);if(!stalled)queueMicrotask(()=>{this.onopen?.();this.onmessage?.({data:JSON.stringify({type:'presence',online:true})})})}send(value){if(value==='ping')return;const m=JSON.parse(value);if(m.type==='offer'){const secret=this.url.startsWith('wss://b.')?next.secret:config.secret;const sdp='answer';const mac=createHmac('sha256',secret).update(m.session+'\nanswer\n'+sdp).digest('hex');queueMicrotask(()=>this.onmessage?.({data:JSON.stringify({type:'answer',session:m.session,sdp,mac})}))}}close(){this.readyState=3}}
 const window={NativeBridge:{ready:v=>ready=v,status(){},job(){},busy(){}},addEventListener(){}};
 const context=vm.createContext({window,document:{getElementById:id=>elements[id]},Date:Clock,crypto:webcrypto,TextEncoder,TextDecoder,Uint8Array,atob,btoa,URL,WebSocket:Socket,RTCPeerConnection:Peer,location:{hash:'#'+Buffer.from(JSON.stringify(config)).toString('base64url')},fetch:async url=>{if(delayIce&&url.startsWith(config.service)){return new Promise(resolve=>resolveIce=()=>resolve({ok:true,json:async()=>({iceServers:[{urls:'a'}]})}))}return{ok:true,json:async()=>({iceServers:[{urls:'b'}]})}},setTimeout,clearTimeout,setInterval:(fn,ms)=>{if(ms===8000)retry=fn;return 0},clearInterval(){},console});vm.runInContext(source,context);
 return {window,sockets,peers,next,isReady:()=>ready,retry:()=>retry(),advance:ms=>now+=ms,hasDelayedIce:()=>!!resolveIce,finishOldIce:()=>resolveIce()};
}
test('closed data channel automatically starts a fresh authenticated connection',async()=>{const f=fixture();try{await until(f.isReady);const first=f.peers[0];first.channel.readyState='closed';first.channel.onclose();assert.equal(f.isReady(),false);f.retry();await until(()=>f.sockets.length===2&&f.isReady());assert.notEqual(f.peers[1],first)}finally{f.window.ActionBridge.dispose()}});
test('stalled signaling handshake reconnects after its deadline',async()=>{const f=fixture({stalled:true});try{assert.equal(f.sockets.length,1);f.advance(36000);f.retry();assert.equal(f.sockets.length,2)}finally{f.window.ActionBridge.dispose()}});
test('delayed ICE response for old PC cannot replace the selected connection',async()=>{const f=fixture({delayIce:true});try{await until(f.hasDelayedIce);f.window.ActionBridge.connect(Buffer.from(JSON.stringify(f.next)).toString('base64url'));await until(f.isReady);f.finishOldIce();await new Promise(r=>setTimeout(r,30));assert.equal(f.peers.length,1);assert.equal(f.peers[0].origin,'b');assert.equal(f.isReady(),true)}finally{f.window.ActionBridge.dispose()}});
